language: node_js
node_js:
  - lts/*
install:
  - npm install
script:
  - npm storybook:build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/docs
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main